import { useEffect } from "react";

interface propTypes {
  title: string
}
const PageHead = ({ title }: propTypes) => {
  useEffect(() => {
    document.title = title
  }, [title])

  return (
    <>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
};

export default PageHead;